baseURL = 'https://example.org/'
theme = 'PaperMod'
locale = 'en-GB'
title = '>_ mads80'


[params]
#env = 'production'
defaultTheme = 'auto'
favicon = '/images/favicon.ico'
hideFooter = false
socialIcons = [
  {name = 'github', url = 'https://github.com/mads80'},
  {name = 'instagram', url = 'https://instagram.com/mads2o5'}
]
showReadingTime = true
showBreadcrumbs = true
showPostNavLinks = true
showCodeCopyButtons = true
showPageNums = true
showToc = true

[params.homeInfoParams]
title = 'Hello, World!'
content = 'Here I will write about my discoveries in tech and my journey through the world.'


[outputs]
home = [
  "HTML",
  "RSS",
  "JSON" # necessary for search
]


# Menu
[[menu.main]]
identifier = 'home'
name = 'Home'
url = '/'
weight = 1

[[menu.main]]
identifier = 'about'
name = 'About'
url = '/about/'
weight = 2

[[menu.main]]
identifier = 'search'
name = 'Search'
url = '/search/'
weight = 3

[[menu.main]]
identifier = 'tags'
name = 'Tags'
url = '/tags'
weight = 4

[[menu.main]]
identifier = 'archives'
name = 'Archives'
url = '/archives/'
weight = 5
